### ISSUE TITLE
ToNumber environment issues.

### ISSUE THREAD

**Issue by Xotic750** [ljharb/es-to-primitive#1]
Several tests have highlighted issues regarding ToNumber conversion. I don't have time to create specific tests here just now, but they are being dealt with in es6-shim.

paulmillr/es6-shim#366

Original identification was in lodash

Original PR lodash/lodash#1577
Actual merge lodash/lodash@3795534

**Comment by ljharb** [comment]
Nothing about `ToPrimitive` actually does number coercion - it simply returns a primitive. The bug deals with `Number('0b12')` - and `'0b12'` is already a primitive. It's now fixed in `es-abstract`. Thanks for reporting!

**Comment by Xotic750** [comment]
Probably not, with lodash it was a case of making sure to check valueOf was a function as some older Operas would crash. You check isCallable, so mute point. The other one was some older environment native objects to string would convert to a string with += '' where toString was badly formed. I haven't looked at your code. Just looked and you use toString, not sure if it a concern for you in such environments.

**Comment by ljharb** [comment]
I use `String(x)` since concatenating to an empty string calls `valueOf` - so I think it should be OK
