### ISSUE TITLE
ToPrimitive has only one required argument

### ISSUE THREAD

**Issue by JakeChampion** [ljharb/es-to-primitive#29]
The version of `ToPrimitive` in this repository has a function length of 2. [`ToPrimitive`](https://tc39.github.io/ecma262/#sec-toprimitive) has a function length of 1 because the second argument is optional according to the specification (`ToPrimitive ( input [ , PreferredType ] )`).

As this is an abstract operation and not available directly to userland application code this is probably not a real issue but I thought it would might be helpful to point out this difference.

**Comment by ljharb** [comment]
Thanks, good catch!
